sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: songzhikang719
  aws:
    s3:
      accessKey: AKIARSU7LD7PH75ESONP
      secretKey: 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
      region: us-east-2
      bucketName: sky-take-out-skkk
  wechat:
    appid: wx11b1a75dad0316c0
    secret: 1e78de356be09bd891ef31308d51af36